//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace XP.Effects
{
    
    public class ColorEffect : ShaderEffect {
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(ColorEffect), 0);
        public static readonly DependencyProperty ColorProperty = 
            DependencyProperty.Register("Color", typeof(Color), typeof(ColorEffect),
            new UIPropertyMetadata(Colors.Transparent, PixelShaderConstantCallback(3)));
        public ColorEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri(@"/XP;component/Effects/Color.ps", UriKind.Relative);
            this.PixelShader = pixelShader;

            this.UpdateShaderValue(InputProperty);
            this.UpdateShaderValue(ColorProperty);
        }

        public ColorEffect(Color color)
        {
            this.Color = color;

            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri(@"/XP;component/Effects/Color.ps", UriKind.Relative);
            this.PixelShader = pixelShader;

            this.UpdateShaderValue(InputProperty);
            this.UpdateShaderValue(ColorProperty);
        }

        public Brush Input {
            get {
                return ((Brush)(this.GetValue(InputProperty)));
            }
            set {
                this.SetValue(InputProperty, value);
            }
        }
        public Color Color {
            get {
                return ((Color)(this.GetValue(ColorProperty)));
            }
            set {
                this.SetValue(ColorProperty, value);
            }
        }
    }
}
